# Generated by Django 4.2.7 on 2023-12-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_user_auctionitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='image_url',
            field=models.URLField(default='https://user-images.githubusercontent.com/52632898/161646398-6d49eca9-267f-4eab-a5a7-6ba6069d21df.png'),
        ),
    ]
