# Generated by Django 4.2.7 on 2023-12-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='bid_counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='starting_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
